language: go

go:
  - 1.7.x

install:
  - wget https://github.com/google/protobuf/archive/v3.3.0.tar.gz
  - tar -xzvf v3.3.0.tar.gz
  - pushd protobuf-3.3.0 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd
  - rm -rf protobuf-3.3.0
  - go get -u github.com/Masterminds/glide
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - glide install

script: 
  - touch .env
  - ./auto/travis/proto.sh
  - ./auto/travis/test.sh
  - go vet $(go list ./... | grep -vi 'vendor\|testing')

after_success:
  - bash <(curl -s https://codecov.io/bash)
