dist: trusty
language: go
go:
  - 1.8
install:
  - sudo apt-get install unzip
  - wget https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
  - sudo unzip protoc-3.3.0-linux-x86_64.zip -d /usr/local/protoc-3.3.0
  - export PATH=${PATH}:/usr/local/protoc-3.3.0/bin
  - protoc --version
script: 
  - touch .env
  - make
  - make test
